export default function sitemap() {
  const baseUrl = "https://www.quiktoolkit.com";

  const routeDates = {
    "": "2026-06-01",
    "/pdf": "2026-05-15",
    "/pdf/merge": "2026-05-15",
    "/pdf/split": "2026-05-15",
    "/pdf/compress": "2026-05-15",
    "/pdf/pdf-to-text": "2026-05-15",
    "/calculators": "2026-05-20",
    "/calculators/emi": "2026-05-20",
    "/calculators/bmi": "2026-05-20",
    "/calculators/age": "2026-05-20",
    "/calculators/percentage": "2026-05-20",
    "/converters": "2026-05-20",
    "/converters/unit": "2026-05-20",
    "/converters/currency": "2026-05-20",
    "/converters/color": "2026-05-20",
    "/text-tools": "2026-05-25",
    "/text-tools/word-counter": "2026-05-25",
    "/text-tools/case-converter": "2026-05-25",
    "/text-tools/text-reverser": "2026-05-25",
    "/text-tools/remove-duplicates": "2026-05-25",
    "/image-tools": "2026-05-20",
    "/image-tools/compress": "2026-05-20",
    "/image-tools/resize": "2026-05-20",
    "/image-tools/image-to-pdf": "2026-05-20",
    "/image-tools/convert-format": "2026-05-20",
    "/developer-tools": "2026-05-25",
    "/developer-tools/json-formatter": "2026-05-25",
    "/developer-tools/qr-code": "2026-05-25",
    "/developer-tools/regex-tester": "2026-05-25",
    "/developer-tools/password-generator": "2026-05-25",
    "/finance": "2026-06-01",
    "/about": "2026-06-01",
    "/contact": "2026-06-01",
    "/privacy-policy": "2026-06-01",
    "/terms": "2026-06-01",
  };

  const routes = [
    "",
    "/about",
    "/contact",
    "/privacy-policy",
    "/terms",
    // PDF Tools
    "/pdf",
    "/pdf/compress",
    "/pdf/merge",
    "/pdf/split",
    "/pdf/pdf-to-text",
    // Calculators
    "/calculators",
    "/calculators/percentage",
    "/calculators/bmi",
    "/calculators/age",
    "/calculators/emi",
    "/calculators/tip",
    "/calculators/discount",
    "/calculators/scientific",
    "/calculators/gpa",
    "/calculators/abfindung",
    // Finance
    "/finance",
    "/finance/loan-calculator",
    "/finance/compound-interest",
    "/finance/salary-calculator",
    "/finance/invoice-generator",
    "/finance/vat-calculator",
    "/finance/french-tax-calculator",
    "/finance/brutto-netto",
    "/finance/mehrwertsteuer",
    "/finance/german-grade-calculator",
    "/finance/kurzarbeit",
    "/finance/elterngeld",
    "/finance/netherlands-tax",
    "/finance/netherlands-btw",
    "/finance/netherlands-30-percent",
    "/finance/netherlands-mortgage",
    "/finance/netherlands-zzp",
    "/finance/netherlands-toeslagen",
    "/finance/singapore-income-tax",
    "/finance/singapore-cpf",
    "/finance/singapore-stamp-duty",
    "/finance/singapore-hdb-loan",
    "/finance/singapore-cpf-retirement",
    "/finance/singapore-gst",
    "/finance/singapore-property-tax",
    "/finance/india-income-tax",
    "/finance/india-gst",
    "/finance/india-sip",
    "/finance/india-hra",
    "/finance/india-ppf",
    "/finance/india-epf",
    "/finance/india-gratuity",
    "/finance/india-fd",
    "/finance/india-home-loan",
    "/finance/india-ctc",
    "/finance/canada-income-tax",
    "/finance/canada-gst-hst",
    "/finance/canada-mortgage",
    "/finance/canada-rrsp",
    "/finance/canada-tfsa",
    "/finance/canada-cpp",
    "/finance/canada-hst-reverse",
    "/finance/sri-lanka-salary",
    "/finance/sri-lanka-epf",
    "/finance/sri-lanka-vehicle",
    "/finance/sri-lanka-income-tax",
    "/finance/sri-lanka-stamp-duty",
    "/finance/sri-lanka-fixed-deposit",
    "/finance/sri-lanka-vat",
    "/finance/ireland-tax",
    "/finance/ireland-vat",
    "/finance/ireland-mortgage",
    "/finance/ireland-rent-tax-credit",
    "/finance/ireland-stamp-duty",
    "/finance/ireland-usc",
    "/finance/ireland-pension",
    // Health
    "/health",
    "/health/calorie-calculator",
    "/health/water-intake",
    "/health/ideal-weight",
    "/health/body-fat",
    "/health/sleep-calculator",
    "/health/calories-burned",
    "/health/pregnancy-due-date",
    "/health/running-pace",
    // Converters
    "/converters",
    "/converters/unit",
    "/converters/currency",
    "/converters/color",
    "/converters/timezone",
    "/converters/number-base",
    "/converters/clothing-size",
    "/converters/cooking-units",
    "/converters/german-units",
    "/converters/euro-converter",
    // Text Tools
    "/text-tools",
    "/text-tools/word-counter",
    "/text-tools/case-converter",
    "/text-tools/text-reverser",
    "/text-tools/remove-duplicates",
    "/text-tools/lorem-ipsum",
    "/text-tools/text-to-slug",
    "/text-tools/line-counter",
    "/text-tools/sort-lines",
    "/text-tools/text-compare",
    "/text-tools/html-encode",
    "/text-tools/text-to-speech",
    "/text-tools/palindrome",
    "/text-tools/text-to-binary",
    "/text-tools/morse-code",
    "/text-tools/number-to-words",
    "/text-tools/remove-spaces",
    "/text-tools/add-line-numbers",
    "/text-tools/transliteration",
    "/text-tools/cyrillic-latin",
    // Image Tools
    "/image-tools",
    "/image-tools/compress",
    "/image-tools/resize",
    "/image-tools/image-to-pdf",
    "/image-tools/convert-format",
    "/image-tools/photo-print-size",
    "/tools/screen-resolution",
    // Developer Tools
    "/developer-tools",
    "/developer-tools/password-generator",
    "/developer-tools/json-formatter",
    "/developer-tools/qr-code",
    "/developer-tools/regex-tester",
    "/developer-tools/base64",
    "/developer-tools/url-encoder",
    "/developer-tools/markdown",
    "/developer-tools/uuid-generator",
    "/developer-tools/hash-generator",
    "/developer-tools/json-to-csv",
    "/developer-tools/html-encoder",
    "/developer-tools/image-to-base64",
    "/developer-tools/css-gradient",
    "/developer-tools/password-strength",
    // SEO Tools
    "/seo-tools",
    "/seo-tools/meta-tag-generator",
    "/seo-tools/word-density",
    // Timer Tools
    "/timer-tools",
    "/timer-tools/stopwatch",
    "/timer-tools/countdown-timer",
    "/timer-tools/pomodoro",
    // Random Tools
    "/random-tools",
    "/random-tools/random-number",
    "/random-tools/coin-flip",
    "/random-tools/random-name-picker",
    "/random-tools/spin-wheel",
    // Math Tools
    "/math-tools",
    "/math-tools/fraction-calculator",
    "/math-tools/percentage-change",
    "/math-tools/prime-checker",
    "/math-tools/lcm-gcd",
    "/math-tools/quadratic",
    "/math-tools/standard-deviation",
    "/math-tools/roman-numerals",
    "/math-tools/area-calculator",
    "/math-tools/volume-calculator",
    "/math-tools/percentage-calc",
    // Date Tools
    "/date-tools",
    "/date-tools/date-difference",
    "/date-tools/days-until",
    "/date-tools/unix-timestamp",
    // Food Tools
    "/food-tools",
    "/food-tools/recipe-converter",
    "/food-tools/cooking-converter",
    "/food-tools/calorie-counter",
    // Student Tools
    "/student-tools",
    "/student-tools/grade-calculator",
    "/student-tools/study-timer",
    "/student-tools/citation-generator",
    // Engineering Tools
    "/engineering",
    "/engineering/ohms-law",
    "/engineering/resistor-color",
    "/engineering/aspect-ratio",
    "/engineering/ppi-calculator",
    // Games
    "/games",
    "/games/reaction-time",
    "/games/typing-speed",
    "/games/rock-paper-scissors",
    "/games/memory-game",
    // PDF addition
    "/pdf/word-count",
  ];

  return routes.map((route) => ({
    url: `${baseUrl}${route}`,
    lastModified: new Date(routeDates[route] || "2026-05-01"),
    changeFrequency: route === "" ? "daily" : "weekly",
    priority: route === "" ? 1 : route.split("/").length === 2 ? 0.8 : 0.6,
  }));
}
